### ISSUE TITLE
Decryption fail :(

### ISSUE THREAD

**Issue by puritas** [wjdwndud0114/REinca#1]
Hi! I'm trying to decrypt another inca appguard apk, but we have different classes and filestructure so running your tool as-is doesn't decrypt. 

Tried to edit the getkeys function to match the classes in my inca folder, but I actually can't figure out what's going on in there so no joy.

Any suggestions, or would it be possible to purchase your time? 

Thanks in advance

**Comment by wjdwndud0114** [comment]
Late reply :) but I'm sure there are different obfuscation options and techniques that you would have to manually reverse engineer
